package com.nexonai.unpruuf.screens.qrpair

import com.nexonai.unpruuf.domain.AppEdition
import com.nexonai.unpruuf.domain.network.RelayManager

/**
 * The cross-platform (iOS-interop) pairing QR — see CROSS_PLATFORM_PLAN.md. Structurally
 * different from [QrPairingPayload] (which is onion-based), not a version bump of it: there's
 * no onion address here, only a relay connection pool ("n", playing the role Android's "o"
 * plays elsewhere — "the address(es) others should use to reach me"). This is the Android-side
 * counterpart of iOS's `PairingPayload.swift`; the wire format below is byte-for-byte what that
 * file already implements, since iOS shipped first and this is the companion piece.
 *
 * Also the pairing format used for Android↔Android contacts under `RelayManager.RelayMode.
 * MANDATORY` since v1.10 (see CHANGELOG "Business/Mandatory pairing unification") — not just
 * iOS interop. `appEdition` exists for that reason: iOS never sends it (no Standard/Client
 * concept there — see `AppEdition`'s own doc comment), but two real Android editions pairing
 * this way still need `AppEdition.canAdd()` enforced, which needs to know the sender's edition.
 *
 * Wire format: `{"v":2,"u":"<compact userId>","p":"<myMessageKey b64>","k":"<x25519 ratchet
 * pubkey b64>","n":"<relay1>[;<relay2>]"[,"e":"<edition>"]}` — same compact-UUID convention as
 * [QrPairingPayload] (see [compactUserId]/[expandUserId] in QrCodec.kt). `n` holds up to
 * [RelayManager.RELAY_POOL_MAX_SIZE] (2) `;`-joined connection strings rather than one — a small
 * failover pool, not an open-ended list, since each extra entry meaningfully grows the QR.
 */
data class CrossPlatformPairingPayload(
    val version: Int = 2,
    val userId: String,
    val messageKeyBase64: String,
    val x25519RatchetPublicKeyBase64: String,
    val relayConnectionStrings: List<String>,
    // Missing on any QR generated by iOS (no edition concept there) or a pre-this-field Android
    // QR — defaults to STANDARD, which keeps the existing Pro-gated iOS-interop path's
    // AppEdition.canAdd() check passing exactly as it did before this field existed.
    val appEdition: String = AppEdition.STANDARD
)

fun crossPlatformPayloadToJson(payload: CrossPlatformPairingPayload): String {
    val compact = compactUserId(payload.userId) ?: payload.userId
    val n = escape(RelayManager.buildConnectionStringList(payload.relayConnectionStrings))
    return """{"v":${payload.version},"u":"$compact","p":"${payload.messageKeyBase64}","k":"${payload.x25519RatchetPublicKeyBase64}","n":"$n","e":"${payload.appEdition}"}"""
}

/** Returns null if [json] isn't a cross-platform payload at all (no "n" key, or an "n" that
 *  parses to zero usable relay entries) — the caller is expected to have already tried the
 *  onion-based [QrPairingPayload] parse first, since the two formats aren't distinguished by an
 *  explicit type tag, only by which fields are present. Accepts both today's list-valued `n` and
 *  a pre-pool single-entry `n` (a QR from an older app version) — a lone entry is just one valid
 *  list, no special-casing needed to accept it. */
fun jsonToCrossPlatformPayload(json: String): CrossPlatformPairingPayload? {
    return try {
        val map = parseSimpleJson(json)
        val compact = map["u"] ?: return null
        val n = map["n"] ?: return null
        val relays = RelayManager.parseConnectionStringList(unescape(n)).take(RelayManager.RELAY_POOL_MAX_SIZE)
        if (relays.isEmpty()) return null
        CrossPlatformPairingPayload(
            version = map["v"]?.toIntOrNull() ?: 1,
            userId = expandUserId(compact) ?: return null,
            messageKeyBase64 = map["p"] ?: return null,
            x25519RatchetPublicKeyBase64 = map["k"] ?: return null,
            relayConnectionStrings = relays,
            appEdition = map["e"] ?: AppEdition.STANDARD
        )
    } catch (e: Exception) {
        null
    }
}

// `n`'s value can't contain a raw '"' or '\' in practice (relay connection strings are bounded to
// a fixed charset — see server/src/identity.ts's generateToken()), but escaping on encode costs
// nothing and matches iOS's PairingPayload.swift, which does the same defensively. Decode-side
// parseSimpleJson() doesn't unescape any field today (not just this one) — matching its existing
// behavior rather than introducing an inconsistency only "n" gets special treatment for.
private fun escape(s: String): String = s.replace("\\", "\\\\").replace("\"", "\\\"")
private fun unescape(s: String): String = s.replace("\\\"", "\"").replace("\\\\", "\\")
