pairs_b = [
 ('Sistemul tău de comunicare. Al nimănui altcuiva.', 'Ihr Kommunikationssystem. Und niemandes sonst.'),
 ('Fără furnizor. Fără cont. Fără ID. Infrastructura ta, cheile tale, nodurile tale.', 'Kein Anbieter. Kein Konto. Keine ID. Ihre Infrastruktur, Ihre Schlüssel, Ihre Nodes.'),
 ('Mesajul central: nu vindem un serviciu de mesagerie. Construim pentru client propriul sistem de comunicare, pe care NexonAI nu îl operează.', 'Kernbotschaft: Wir verkaufen keinen Messenger-Dienst. Wir bauen dem Kunden sein eigenes Kommunikationssystem, das NexonAI nicht betreibt.'),
 ('"Problema", "Fiecare mesager are un proprietar"', '"Das Problem", "Jeder Messenger hat einen Eigentümer"'),
 ('"Serverul furnizorului", "Toate mesajele trec prin infrastructura altcuiva."', '"Server des Anbieters", "Alle Nachrichten laufen über fremde Infrastruktur."'),
 ('"Cont și număr de telefon", "Fiecare utilizator este identificabil de la prima zi."', '"Konto und Telefonnummer", "Jeder Nutzer ist vom ersten Tag an identifizierbar."'),
 ('"Metadate", "Cine, cu cine, când și cât de des — vizibil pentru furnizor."', '"Metadaten", "Wer, mit wem, wann und wie oft — sichtbar für den Anbieter."'),
 ('Chiar și cu criptare cap la cap, furnizorul rămâne a treia parte care poate fi obligată să predea date.', 'Auch mit Ende-zu-Ende-Verschlüsselung bleibt der Anbieter der Dritte, der zur Herausgabe von Daten verpflichtet werden kann.'),
 ('eyebrow("Instrumentul", ON_DARK)', 'eyebrow("Das Werkzeug", ON_DARK)'),
 ('Serverul tău.<br>Sute de noduri proprii.', 'Ihr Server.<br>Hunderte eigene Nodes.'),
 ('<li>Nicăieri înregistrate.</li>\n<li>Doar tu poți scrie pe ele.</li>\n<li>Doar cine este invitat cunoaște o adresă.</li>', '<li>Nirgends registriert.</li>\n<li>Nur Sie können darauf schreiben.</li>\n<li>Nur wer eingeladen ist, kennt eine Adresse.</li>'),
 ('Serverul este instrumentul: cu el, fiecare utilizator își creează propriul sistem de comunicare anonim. NexonAI nu găzduiește nimic.', 'Der Server ist das Werkzeug: Damit baut sich jeder Nutzer sein eigenes anonymes Kommunikationssystem. NexonAI hostet nichts.'),
 ('"Cum funcționează", "Fiecare scrie doar pe nodurile sale"', '"So funktioniert es", "Jeder schreibt nur auf eigene Nodes"'),
 ('"Telefon A", "doar client Tor"', '"Handy A", "reiner Tor-Client"'),
 ('"Telefon B", "doar client Tor"', '"Handy B", "reiner Tor-Client"'),
 ('"Nodurile lui A", "adresă onion fixă"', '"Nodes von A", "feste Onion-Adresse"'),
 ('"Nodurile lui B", "adresă onion fixă"', '"Nodes von B", "feste Onion-Adresse"'),
 ('lbl(220, 425, 380, "depune (cheie de scriere)")', 'lbl(220, 425, 380, "ablegen (Schreibschlüssel)")'),
 ('lbl(1300, 425, 380, "preia (cod de preluare)")', 'lbl(1300, 425, 380, "abholen (Abhol-Code)")'),
 ('lbl(1300, 745, 420, "depune (cheie de scriere)")', 'lbl(1300, 745, 420, "ablegen (Schreibschlüssel)")'),
 ('lbl(180, 745, 380, "preia (cod de preluare)")', 'lbl(180, 745, 380, "abholen (Abhol-Code)")'),
 ('"totul prin Tor"', '"alles über Tor"'),
 ('A scrie pe nodurile proprii, B preia de acolo. Drumul înapoi trece prin nodurile lui B. Nimeni nu scrie pe nodurile altcuiva.', 'A schreibt auf seine eigenen Nodes, B holt dort ab. Der Rückweg läuft über die Nodes von B. Niemand schreibt auf fremde Nodes.'),
 ('"Identificare", "Două coduri. Atât."', '"Identifikation", "Zwei Codes. Mehr nicht."'),
 ('big("Codul de preluare", "Găsește mesajul fără să numească pe nimeni. Se schimbă din oră în oră, calculat independent de ambele părți.", TEAL)', 'big("Der Abhol-Code", "Findet die Nachricht, ohne jemanden zu nennen. Wechselt stündlich, beide Seiten berechnen ihn selbst.", TEAL)'),
 ('big("Cheia de decriptare", "Face conținutul lizibil. O au doar cei doi parteneri de conversație — nimeni altcineva.", ORANGE)', 'big("Der Schlüssel", "Macht den Inhalt lesbar. Ihn haben nur die beiden Gesprächspartner — sonst niemand.", ORANGE)'),
 ('Aplicația nu știe cu cine vorbește. Are nevoie doar de un cod pentru a găsi și de unul pentru a decripta.', 'Die App weiß nicht, mit wem sie spricht. Sie braucht nur einen Code zum Finden und einen zum Entschlüsseln.'),
 ('"Ce nu există", "Nimic de identificat"', '"Was es nicht gibt", "Nichts, was identifiziert"'),
 ('gone("ID de utilizator")', 'gone("Benutzer-ID")'),
 ('gone("Număr de telefon")', 'gone("Telefonnummer")'),
 ('gone("Cont")', 'gone("Konto")'),
 ('gone("Adresă onion pe telefon")', 'gone("Onion-Adresse auf dem Handy")'),
 ('gone("Furnizor")', 'gone("Anbieter")'),
 ('gone("Lucruri comune între contacte")', 'gone("Gemeinsames zwischen Kontakten")'),
 ('Fiecare asociere primește chei noi și noduri proprii. Doi contacți care își compară codurile QR nu găsesc nimic comun.', 'Jedes Pairing bekommt neue Schlüssel und eigene Nodes. Zwei Kontakte, die ihre QR-Codes vergleichen, finden nichts Gemeinsames.'),
 ('"Scalare", "Sute de noduri, câte 3 pentru fiecare contact"', '"Skalierung", "Hunderte Nodes, je 3 pro Kontakt"'),
 ('num("500", "noduri pe un singur server, într-un singur proces", TEAL)', 'num("500", "Nodes auf einem Server, in einem einzigen Prozess", TEAL)'),
 ('num("3", "noduri proprii pentru fiecare contact nou", ORANGE)', 'num("3", "eigene Nodes für jeden neuen Kontakt", ORANGE)'),
 ('num("0", "lucruri comune între doi contacți, cu un grup suficient de mare", TEAL)', 'num("0", "Gemeinsamkeiten zwischen zwei Kontakten, bei genug Nodes im Pool", TEAL)'),
 ('O singură scanare QR per server: aplicația preia singură celelalte noduri și dă fiecărui contact nodurile lui. Un nod confiscat atinge doar câțiva contacți, nu pe toți.', 'Ein QR-Scan pro Server: Die App holt sich die übrigen Nodes selbst und gibt jedem Kontakt seine eigenen. Ein beschlagnahmter Node betrifft nur wenige Kontakte, nicht alle.'),
 ('Măsurat fără rețeaua Tor live: 500 de noduri într-un proces aproximativ 85 MB RAM. Sarcina de rețea pe un VPS real urmează să fie măsurată.', 'Gemessen ohne Live-Tor-Netz: 500 Nodes in einem Prozess rund 85 MB RAM. Die Netzlast auf einem echten VPS wird noch gemessen.'),
 ('"Nodul", "Ce vede nodul — și ce nu"', '"Der Node", "Was der Node sieht — und was nicht"'),
 ('card("Vede", "Blocuri criptate de mărime fixă, sub coduri care se schimbă din oră în oră. Le șterge singur după 1 până la 24 de ore.", bg=CARD)', 'card("Sieht", "Verschlüsselte Blöcke fester Größe unter stündlich wechselnden Codes. Löscht sie selbst nach 1 bis 24 Stunden.", bg=CARD)'),
 ('card("Nu vede", "Conținutul. Expeditorul. Destinatarul. Adresa IP. Cine aparține de cine.", bg=DARK, border=DARK, tcolor=ON_DARK, bcolor=ON_DARK_MUTED)', 'card("Sieht nicht", "Den Inhalt. Den Absender. Den Empfänger. Die IP-Adresse. Wer zu wem gehört.", bg=DARK, border=DARK, tcolor=ON_DARK, bcolor=ON_DARK_MUTED)'),
 ('Un nod confiscat nu conține nimic de citit.', 'Ein beschlagnahmter Node enthält nichts Lesbares.'),
 ('"Serverul în practică", "Instalare fără linie de comandă"', '"Der Server in der Praxis", "Installation ohne Kommandozeile"'),
 ('card("Oriunde", "Windows, Linux, Docker, fișier .exe sau o tabletă Android ca nod.", pad=36)', 'card("Überall", "Windows, Linux, Docker, als .exe oder ein Android-Tablet als Node.", pad=36)'),
 ('card("Configurare", "install.bat și start.bat. Pagina de configurare arată codul QR pentru propria aplicație.", pad=36)', 'card("Einrichtung", "install.bat und start.bat. Die Einrichtungsseite zeigt den QR-Code für die eigene App.", pad=36)'),
 ('card("Profiluri", "Standard 6 ore, securitate ridicată 1 oră, tolerant offline 24 de ore.", pad=36)', 'card("Profile", "Standard 6 Stunden, hohe Sicherheit 1 Stunde, offline-tolerant 24 Stunden.", pad=36)'),
 ('card("Nod temporar", "Doar pentru o conversație, doar în memorie. Închis = dispărut.", pad=36)', 'card("Temp Node", "Nur für ein Gespräch, nur im Arbeitsspeicher. Geschlossen = weg.", pad=36)'),
 ('"Securitate integrată", "Cinci straturi, nicio promisiune"', '"Eingebaute Sicherheit", "Fünf Schichten, kein Versprechen"'),
 ('pill("Tor obligatoriu", "Nodul nu vede niciodată o adresă IP.")', 'pill("Tor verpflichtend", "Der Node sieht nie eine IP-Adresse.")'),
 ('pill("Proof-of-Work", "Supraîncărcarea nodului costă atacatorul putere de calcul.")', 'pill("Proof-of-Work", "Den Node zu überfluten kostet den Angreifer Rechenleistung.")'),
 ('pill("Scriere doar de proprietar", "Nimeni altcineva nu poate depune pe nodurile tale.")', 'pill("Nur der Besitzer schreibt", "Niemand sonst kann auf Ihren Nodes ablegen.")'),
 ('pill("Double Ratchet", "Chei noi pentru fiecare mesaj, mesajele vechi rămân protejate.")', 'pill("Double Ratchet", "Neue Schlüssel für jede Nachricht, alte bleiben geschützt.")'),
 ('pill("Chei proprii per contact", "Fiecare asociere are propriile chei și noduri.")', 'pill("Eigene Schlüssel pro Kontakt", "Jedes Pairing hat eigene Schlüssel und Nodes.")'),
 ('eyebrow("Conformitate prin arhitectură", "#F0B27A")', 'eyebrow("Compliance durch Architektur", "#F0B27A")'),
 ('Nu există niciun furnizor care să poată fi obligat să predea date.', 'Es gibt keinen Anbieter, der zur Herausgabe von Daten verpflichtet werden kann.'),
 ('NexonAI nu găzduiește nimic și nu prelucrează date în numele clientului.', 'NexonAI hostet nichts und verarbeitet keine Daten im Auftrag des Kunden.'),
 ('Protecția datelor din faza de proiectare (art. 25 GDPR).', 'Datenschutz durch Technikgestaltung (Art. 25 DSGVO).'),
 ('Datele rămân exclusiv în infrastructura proprie.', 'Die Daten bleiben ausschließlich in der eigenen Infrastruktur.'),
 ('Formulare atentă: nu spunem că citațiile sau ordinele judecătorești sunt inutile. Spunem că nu există un furnizor care să predea ceva și că un nod confiscat nu conține nimic lizibil.', 'Vorsichtig formulieren: Wir sagen nicht, dass Durchsuchungen oder Anordnungen sinnlos sind. Wir sagen, dass es keinen Anbieter gibt, der etwas herausgeben könnte, und dass ein beschlagnahmter Node nichts Lesbares enthält.'),
 ('"Pentru cine", "Oriunde confidențialitatea este o obligație"', '"Für wen", "Überall, wo Vertraulichkeit Pflicht ist"'),
 ('small("Avocați", "Comunicare cu clienții protejată de secretul profesional.")', 'small("Kanzleien", "Mandanten-Kommunikation unter Berufsgeheimnis.")'),
 ('small("Sănătate", "Date medicale fără furnizor terț.")', 'small("Gesundheit", "Patientendaten ohne Drittanbieter.")'),
 ('small("Fiscal", "Documente financiare sensibile.")', 'small("Steuern", "Sensible Finanzunterlagen.")'),
 ('small("Conducere", "Decizii strategice, fuziuni, achiziții.")', 'small("Führung", "Strategie, Fusionen, Übernahmen.")'),
 ('small("Autorități", "Comunicare internă fără cloud străin.")', 'small("Behörden", "Interne Kommunikation ohne fremde Cloud.")'),
 ('"Stadiu actual", "Construit și testat. Următorul pas: dispozitive reale."', '"Aktueller Stand", "Gebaut und getestet. Nächster Schritt: echte Geräte."'),
 ('card("Gata", "Server: 41 de teste automate, Tor real. Aplicație: 59 de teste în toate cele 4 ediții. Nod pe tabletă: 9 teste.")', 'card("Fertig", "Server: 41 automatische Tests, echtes Tor. App: 59 Tests in allen 4 Editionen. Tablet-Node: 9 Tests.")'),
 ('card("Urmează", "Test pe dispozitive reale. Măsurarea pe un VPS real. Audit de securitate independent.", bg=LIGHT2)', 'card("Als Nächstes", "Test auf echten Geräten. Messung auf einem echten VPS. Unabhängiges Sicherheits-Audit.", bg=LIGHT2)'),
 ('Nicio arhitectură nu protejează un telefon compromis de programe spion sau un partener care face capturi de ecran.', 'Keine Architektur schützt vor einem Handy mit Spionage-Software oder einem Partner, der Screenshots macht.'),
 ('eyebrow("Pașii următori", ON_DARK)', 'eyebrow("Nächste Schritte", ON_DARK)'),
 ('Un pilot.<br>Sistemul vostru.', 'Ein Pilot.<br>Ihr System.'),
 ('<li>Analiza nevoilor și a fluxurilor de comunicare</li>\n<li>Instalarea serverului propriu și a aplicațiilor</li>\n<li>Pilot cu o echipă, apoi extindere</li>', '<li>Bedarf und Kommunikationswege analysieren</li>\n<li>Eigenen Server und Apps installieren</li>\n<li>Pilot mit einem Team, dann ausrollen</li>'),
 ('"Problema: fiecare mesager are un proprietar."', '"Das Problem: Jeder Messenger hat einen Eigentümer."'),
 ('"Soluția: serverul propriu, nodurile proprii, două coduri."', '"Die Lösung: eigener Server, eigene Nodes, zwei Codes."'),
 ('"Securitate și conformitate prin arhitectură."', '"Sicherheit und Compliance durch Architektur."'),
 ('"Pentru cine, stadiu actual și pașii următori."', '"Für wen, aktueller Stand und nächste Schritte."'),
 ('write_deck("business", "unpruuf Business", S, sections)', 'write_deck("business_de", "unpruuf Business (DE)", S, sections)'),
]
s = open("business.py").read()
for a, b in pairs_b:
    assert a in s, ("missing", a[:70])
    s = s.replace(a, b)
open("business_de.py", "w").write(s)
print("ok")
