pairs = [
 ('Canal de raportare anonim prin arhitectură.', 'Anonymer Meldekanal durch Architektur.'),
 ('Conform Directivei (UE) 2019/1937 și Legii nr. 361/2022. Operat de organizație, nu de un furnizor.', 'Nach EU-Richtlinie 2019/1937 und dem jeweiligen nationalen Gesetz. Betrieben von der Organisation, nicht von einem Anbieter.'),
 ('"Ziua 0", "Raportul sosește", "Cazul se deschide în panou, cu ambele termene pornite automat."', '"Tag 0", "Die Meldung kommt an", "Der Fall öffnet sich im Dashboard, beide Fristen laufen automatisch."'),
 ('"7 zile", "Confirmarea primirii", "Art. 9 alin. (1) lit. b) din directivă."', '"7 Tage", "Eingangsbestätigung", "Art. 9 Abs. 1 Buchst. b der Richtlinie."'),
 ('"3 luni", "Răspuns către avertizor", "Art. 9 alin. (1) lit. f) din directivă."', '"3 Monate", "Rückmeldung an den Hinweisgeber", "Art. 9 Abs. 1 Buchst. f der Richtlinie."'),
 ('"Obligația", "Canal intern de raportare, cu termene clare"', '"Die Pflicht", "Interner Meldekanal mit klaren Fristen"'),
 ('Organizațiile cu 50 sau mai mulți angajați trebuie să ofere un canal intern de raportare.', 'Organisationen mit 50 oder mehr Beschäftigten müssen einen internen Meldekanal anbieten.'),
 ('"Problema soluțiilor clasice", "Anonimatul depinde de o promisiune"', '"Das Problem klassischer Lösungen", "Anonymität hängt an einem Versprechen"'),
 ('card("Platforme SaaS", "Furnizorul ar putea citi tehnic conținutul și metadatele.")', 'card("SaaS-Plattformen", "Der Anbieter könnte Inhalt und Metadaten technisch mitlesen.")'),
 ('card("E-mail și telefon", "Adresa, numărul și ora apelului identifică avertizorul.")', 'card("E-Mail und Telefon", "Adresse, Nummer und Uhrzeit verraten den Hinweisgeber.")'),
 ('card("Contract", "Încrederea stă într-un document, nu în tehnologie.")', 'card("Vertrag", "Das Vertrauen steckt in einem Dokument, nicht in der Technik.")'),
 ('Cine se teme de represalii nu raportează pe un canal în care trebuie să aibă încredere.', 'Wer Repressalien fürchtet, meldet nicht über einen Kanal, dem er vertrauen muss.'),
 ('eyebrow("Instrumentul", ON_DARK)', 'eyebrow("Das Werkzeug", ON_DARK)'),
 ('Releul vostru.<br>Pe hardware-ul vostru.', 'Ihr Relay.<br>Auf Ihrer Hardware.'),
 ('<li>O tabletă sau un laptop al organizației.</li>\n<li>NexonAI nu găzduiește nimic.</li>\n<li>Mai multe canale separate, fiecare cu cheile lui.</li>', '<li>Ein Tablet oder Laptop der Organisation.</li>\n<li>NexonAI hostet nichts.</li>\n<li>Mehrere getrennte Kanäle, jeder mit eigenen Schlüsseln.</li>'),
 ('Mai multe canale înseamnă mai multe relee, fiecare cu propriul panou și propriile chei, de exemplu pe sedii sau departamente.', 'Mehrere Kanäle bedeuten mehrere Relays, jedes mit eigenem Dashboard und eigenen Schlüsseln, zum Beispiel pro Standort oder Abteilung.'),
 ('"Cum funcționează", "Releul nu vede nici conținut, nici identitate"', '"So funktioniert es", "Das Relay sieht weder Inhalt noch Identität"'),
 ('"Aplicația avertizor", "Android, prin Tor"', '"Melder-App", "Android, über Tor"'),
 ('"Panou responsabil", "laptop, prin Tor"', '"Officer-Dashboard", "Laptop, über Tor"'),
 ('"Releul organizației", "cutie poștală oarbă"', '"Eigenes Relay", "blinder Briefkasten"'),
 ('"Raportor web", "browser, fără instalare"', '"Web-Melder", "Browser, ohne Installation"'),
 ('"cod de asociere, o singură dată"', '"Pairing-Code, einmalig"'),
 ('lbl(260, 600, 360, "trimite / preia")', 'lbl(260, 600, 360, "senden / abholen")'),
 ('lbl(1300, 600, 360, "trimite / preia")', 'lbl(1300, 600, 360, "senden / abholen")'),
 ('Singura excepție de la releu: codul de asociere, schimbat o singură dată la deschiderea cazului. După aceea totul trece prin releu, criptat cap la cap.', 'Einzige Ausnahme vom Relay: der Pairing-Code, einmalig beim Öffnen des Falls ausgetauscht. Danach läuft alles über das Relay, Ende-zu-Ende verschlüsselt.'),
 ('"Ce nu există", "Nimic de identificat"', '"Was es nicht gibt", "Nichts, was identifiziert"'),
 ('gone("Cont")', 'gone("Konto")'),
 ('gone("Adresă de e-mail")', 'gone("E-Mail-Adresse")'),
 ('gone("Număr de telefon")', 'gone("Telefonnummer")'),
 ('gone("Pictogramă vizibilă pe telefon")', 'gone("Sichtbares App-Icon")'),
 ('gone("Adresă onion pe telefon")', 'gone("Onion-Adresse auf dem Handy")'),
 ('gone("Furnizor care citește")', 'gone("Anbieter, der mitliest")'),
 ('Aplicația nu are pictogramă sau marcă vizibilă, ca o privire pe telefon să nu trădeze avertizorul.', 'Die App hat kein sichtbares Icon und kein Branding, damit ein Blick aufs Handy den Hinweisgeber nicht verrät.'),
 ('"Model de securitate", "Cine vede ce"', '"Sicherheitsmodell", "Wer sieht was"'),
 ('<th style="width:40%">Cine</th><th style="width:15%">Conținut</th><th style="width:15%">Identitate</th><th style="width:30%">De ce</th>', '<th style="width:40%">Wer</th><th style="width:15%">Inhalt</th><th style="width:15%">Identität</th><th style="width:30%">Warum</th>'),
 ('<td>Operatorul releului</td><td>Nu</td><td>Nu</td><td>Doar blocuri criptate</td>', '<td>Relay-Betreiber</td><td>Nein</td><td>Nein</td><td>Nur verschlüsselte Blöcke</td>'),
 ('<td>Rețea, partea avertizorului</td><td>Nu</td><td>Nu</td><td>Tor</td>', '<td>Netz, Seite des Hinweisgebers</td><td>Nein</td><td>Nein</td><td>Tor</td>'),
 ('<td>Rețea, partea responsabilului</td><td>Nu</td><td>Nu</td><td>Tor</td>', '<td>Netz, Seite des Officers</td><td>Nein</td><td>Nein</td><td>Tor</td>'),
 ('<td>Rețea, raportor web</td><td>Nu</td><td>Parțial</td><td>Fără Tor implicit</td>', '<td>Netz, Web-Melder</td><td>Nein</td><td>Teilweise</td><td>Kein Tor standardmäßig</td>'),
 ('<td>Responsabilul de conformitate</td><td>Da</td><td>Nu, doar dacă o spune avertizorul</td><td>Dosar local criptat</td>', '<td>Compliance-Officer</td><td>Ja</td><td>Nur wenn genannt</td><td>Lokal verschlüsselte Fallakte</td>'),
 ('"Panoul responsabilului", "Dosare cu termene, nu doar un chat"', '"Officer-Dashboard", "Fallakten mit Fristen, nicht nur ein Chat"'),
 ('Exemplu ilustrativ', 'Beispiel zur Veranschaulichung'),
 ('<th style="width:22%">Caz</th><th style="width:26%">Stare</th><th style="width:26%">Confirmare</th><th style="width:26%">Răspuns</th>', '<th style="width:22%">Fall</th><th style="width:26%">Status</th><th style="width:26%">Bestätigung</th><th style="width:26%">Rückmeldung</th>'),
 ('mrow("[Caz 1]", "Nou", "încă 6 zile", "încă 89 zile", CARD)', 'mrow("[Fall 1]", "Neu", "noch 6 Tage", "noch 89 Tage", CARD)'),
 ('mrow("[Caz 2]", "Confirmat", "făcut", "încă 61 zile", LIGHT2)', 'mrow("[Fall 2]", "Bestätigt", "erledigt", "noch 61 Tage", LIGHT2)'),
 ('mrow("[Caz 3]", "În lucru", "făcut", "încă 12 zile", CARD)', 'mrow("[Fall 3]", "In Arbeit", "erledigt", "noch 12 Tage", CARD)'),
 ('<li>Termenele pornesc automat</li>\n<li>Stare: Nou, Confirmat, În lucru, Închis</li>\n<li>Criptat local, protejat prin parolă</li>\n<li>Integral în limba română</li>', '<li>Fristen starten automatisch</li>\n<li>Status: Neu, Bestätigt, In Arbeit, Abgeschlossen</li>\n<li>Lokal verschlüsselt, mit Passwort geschützt</li>\n<li>Oberfläche auch komplett auf Rumänisch</li>'),
 ('"Două căi de raportare", "Protecție maximă sau fără instalare"', '"Zwei Meldewege", "Maximaler Schutz oder ohne Installation"'),
 ('card("Aplicația", "Prin Tor, mesajele doar în memorie, fără pictogramă vizibilă. Recomandată când există risc de represalii.")', 'card("Die App", "Über Tor, Nachrichten nur im Arbeitsspeicher, kein sichtbares Icon. Empfohlen bei Risiko von Repressalien.")'),
 ('card("Browserul", "Fără instalare, aceeași criptare. Protecție mai slabă: fără Tor implicit. Avertisment vizibil pe pagină.", bg=LIGHT2)', 'card("Der Browser", "Ohne Installation, gleiche Verschlüsselung. Schwächerer Schutz: kein Tor standardmäßig. Sichtbarer Warnhinweis.", bg=LIGHT2)'),
 ('"Cadrul legal", "Software care sprijină procesul"', '"Rechtsrahmen", "Software, die den Prozess unterstützt"'),
 ('leg("Art. 9 (1) b)", "Confirmarea primirii în 7 zile — termen calculat automat.")', 'leg("Art. 9 (1) b)", "Eingangsbestätigung in 7 Tagen — Frist wird automatisch berechnet.")'),
 ('leg("Art. 9 (1) f)", "Răspuns către avertizor în 3 luni — termen calculat automat.")', 'leg("Art. 9 (1) f)", "Rückmeldung in 3 Monaten — Frist wird automatisch berechnet.")'),
 ('leg("Art. 16", "Confidențialitatea identității — asigurată prin arhitectură.")', 'leg("Art. 16", "Vertraulichkeit der Identität — durch die Architektur.")'),
 ('Nu este consultanță juridică și nici certificare. Conformitatea completă cu Legea nr. 361/2022 o confirmă departamentul juridic al organizației.', 'Keine Rechtsberatung und keine Zertifizierung. Ob das nationale Umsetzungsgesetz vollständig erfüllt ist, bestätigt die Rechtsabteilung der Organisation.'),
 ('"Instalare", "Trei pași, fără linie de comandă"', '"Installation", "Drei Schritte, ohne Kommandozeile"'),
 ('step("1", "Releul", "Aplicația de releu pe o tabletă Android sau pe un laptop.", TEAL)', 'step("1", "Das Relay", "Die Relay-App auf einem Android-Tablet oder einem Laptop.", TEAL)'),
 ('step("2", "Panoul", "install.bat și start.bat pe laptopul responsabilului.", ORANGE)', 'step("2", "Das Dashboard", "install.bat und start.bat auf dem Laptop des Officers.", ORANGE)'),
 ('step("3", "Comunicarea", "Codul QR sau linkul de raportare pentru angajați.", TEAL)', 'step("3", "Bekanntmachen", "QR-Code oder Melde-Link für die Beschäftigten.", TEAL)'),
 ('"Stadiu actual", "Testat. Următorul pas: dispozitive reale."', '"Aktueller Stand", "Getestet. Nächster Schritt: echte Geräte."'),
 ('card("Gata", "Criptarea verificată octet cu octet. Două implementări independente testate una față de cealaltă. Aplicația: 59 de teste.")', 'card("Fertig", "Verschlüsselung Byte für Byte geprüft. Zwei unabhängige Umsetzungen gegeneinander getestet. App: 59 Tests.")'),
 ('card("Urmează", "Test pe dispozitive reale. Acces pentru mai mulți responsabili. Export de cazuri. Audit independent.", bg=LIGHT2)', 'card("Als Nächstes", "Test auf echten Geräten. Zugang für mehrere Officer. Export von Fällen. Unabhängiges Audit.", bg=LIGHT2)'),
 ('eyebrow("Pașii următori", ON_DARK)', 'eyebrow("Nächste Schritte", ON_DARK)'),
 ('Un pilot.<br>Canalul vostru.', 'Ein Pilot.<br>Ihr Kanal.'),
 ('<li>Analiza cerințelor și a procesului intern</li>\n<li>Instalarea releului și a panoului</li>\n<li>Pilot, apoi lansarea către angajați</li>', '<li>Anforderungen und internen Prozess analysieren</li>\n<li>Relay und Dashboard installieren</li>\n<li>Pilot, dann Start für die Beschäftigten</li>'),
 ('"Obligația legală și problema soluțiilor clasice."', '"Die gesetzliche Pflicht und das Problem klassischer Lösungen."'),
 ('"Soluția: releul organizației, fără nimic de identificat."', '"Die Lösung: das Relay der Organisation, nichts, was identifiziert."'),
 ('"Panou, căi de raportare și cadrul legal."', '"Dashboard, Meldewege und Rechtsrahmen."'),
 ('"Instalare, stadiu și pașii următori."', '"Installation, Stand und nächste Schritte."'),
 ('write_deck("compliance", "unpruuf Compliance", S, sections)', 'write_deck("compliance_de", "unpruuf Compliance (DE)", S, sections)'),
]
s = open("compliance.py").read()
for a, b in pairs:
    assert a in s, ("missing", a[:70])
    s = s.replace(a, b)
open("compliance_de.py", "w").write(s)
print("ok")
